site_name: Test Fixtures
site_description: Reusable PHPUnit fixtures for CiviCRM extensions
site_author: SYSTOPIA
repo_url: https://github.com/systopia/civicrm-test-fixtures

theme:
  name: material

nav:
  - Introduction: index.md
  - Builders: builders.md
  - Scenarios: scenarios.md
  - Fixture Bags: bags.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
